select * from users;
SELECT * FROM ROLES;
SELECT * FROM USER_ROLES;
select * from courses;
select * from ENROLMENTS;
CREATE TABLE IF NOT EXISTS ROLES(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL,
	DESCRITPTION VARCHAR(50),
	CREATED_ON DATE,
	MODIFIED_ON DATE,
	STATUS VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS USER_ROLES(
	ID INT PRIMARY KEY NOT NULL,
	USER_ID INT,
	ROLE_ID INT,
	CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID),
	CREATED_ON DATE,
	MODIFIED_ON DATE,
	STATUS VARCHAR(2)
);


CREATE TABLE IF NOT EXISTS COURSES(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL,
	DESCRITPTION VARCHAR(50),
	TYPE VARCHAR(50),
	AUTHOR_ID INT,
	CREATED_BY INT,
	GROUP_LINK INT,
	START_DATE DATE,
	CREATED_ON DATE,
	MODIFIED_ON DATE,
	STATUS VARCHAR(2)
);


CREATE TABLE IF NOT EXISTS ENROLMENTS(
	ID INT PRIMARY KEY NOT NULL,
	USER_ID INT,
	COURSE_ID INT,
	CREATED_ON DATE,
	STATUS VARCHAR(20),
	CONSTRAINT FK_ENROLMENTS_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_ENROLMENTS_COURSE FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);

CREATE TABLE IF NOT EXISTS COURSE_EVENTS(
	ID INT PRIMARY KEY NOT NULL,
	COURSE_ID INT,
	EVENT_TYPE VARCHAR(50),
	EVENT_NAME VARCHAR(50),
	EVENT_DESCRIPTION VARCHAR(50),
	EVENT_DATE DATE,
	STATUS VARCHAR(2),
	CONSTRAINT FK_COURSE_EVENTS_COURSE FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);


CREATE TABLE IF NOT EXISTS COURSE_NOTIFICATIONS(
	ID INT PRIMARY KEY NOT NULL,
	COURSE_ID INT,
	NOTIFICATION_TYPE VARCHAR(50),
	NOTIFICATION_DESCRIPTION VARCHAR(5000),
	CREATED_ON DATE,
	STATUS VARCHAR(2),
	CONSTRAINT FK_COURSE_EVENTS_COURSE FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);


CREATE TABLE IF NOT EXISTS TODOS(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL,
	DESCRITPTION VARCHAR(50),
	CREATED_ON DATE,
	MODIFIED_ON DATE,
	STATUS VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS PAYMENTS(
	ID INT PRIMARY KEY NOT NULL,
	TYPE TEXT NOT NULL,
	AMOUNT INT,
	PAYMENT_DATE DATE,
	STATUS VARCHAR(2)
);