CREATE TABLE IF NOT EXISTS COURSE_EVENTS(
	ID INT PRIMARY KEY NOT NULL,
	COURSE_ID INT,
	EVENT_TYPE VARCHAR(50),
	EVENT_NAME VARCHAR(50),
	EVENT_DESCRIPTION VARCHAR(50),
	EVENT_DATE DATE,
	STATUS VARCHAR(2),
	CONSTRAINT FK_COURSE_EVENTS_COURSE FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);