--create table users
CREATE TABLE IF NOT EXISTS USERS(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL,
	PASSWORD VARCHAR(1000),
	AGE INT NOT NULL,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(50),
	DOB DATE DEFAULT CURRENT_DATE,
	SEX VARCHAR(6),
	STATUS VARCHAR(2)
);

