CREATE TABLE IF NOT EXISTS USER_ROLES(
	ID INT PRIMARY KEY NOT NULL,
	USER_ID INT,
	ROLE_ID INT,
	CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID),
	CREATED_ON DATE,
	MODIFIED_ON DATE,
	STATUS VARCHAR(2)
);