CREATE TABLE IF NOT EXISTS ENROLMENTS(
	ID INT PRIMARY KEY NOT NULL,
	USER_ID INT,
	COURSE_ID INT,
	CREATED_ON DATE,
	STATUS VARCHAR(20),
	CONSTRAINT FK_ENROLMENTS_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_ENROLMENTS_COURSE FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);
