--create table users
CREATE TABLE IF NOT EXISTS USERS(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL,
	AGE INT NOT NULL,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(50),
	DOB DATE DEFAULT CURRENT_DATE,
	SEX VARCHAR(6),
	STATUS VARCHAR(2)
);
INSERT INTO USERS(ID, NAME, PASSWORD, AGE, EMAIL, PHONE, DOB, SEX, STATUS )
VALUES (2, 'Sajan', 'asdf', 26, 'sajan@sajan.com', '1234567',
		CURRENT_DATE, 'MALE', 'AC');
